import os

import aiohttp
import discord
from discord.ext import commands

from persistence_context import GuildContextRequired, require_guild_id


AI_BASE_URL = "https://openrouter.ai/api/v1"
AI_MODEL_CHAT = "openai/gpt-4o-mini"
AI_IMAGE_COST = 500

SYSTEM_PROMPT = """
You are 'The Plug', a street-smart, helpful, and chill Discord bot assistant for a Weed Tycoon game called 'Stoney Baloney'.
- You speak in mild slang (bruh, fam, bet, say less), but you are intelligent and clear.
- You help users with game strategy (growing, selling, heists).
- You are loyal to the crew.
- Keep responses concise (under 2000 chars).
- GAME INFO:
  - !plant <strain> to grow weed.
  - !heist to steal money (risk jail).
  - !shop to buy seeds and gear.
  - !process to make hash/wax.
"""


class AI(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.api_key = os.getenv("OPENROUTER_API_KEY") or os.getenv("OPENAI_API_KEY")

    @commands.hybrid_command(name="chat", aliases=["ask", "plug", "yo"])
    @commands.cooldown(1, 5, commands.BucketType.user)
    async def chat(self, ctx, *, message: str):
        """Talk to The Plug (AI)."""
        if not self.api_key:
            return await ctx.send("❌ **AI Error:** API Key is missing.")

        payload = {
            "model": AI_MODEL_CHAT,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": message},
            ],
            "temperature": 0.8,
            "max_tokens": 600,
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://discord.com",
            "X-Title": "Stoney Baloney",
        }

        async with ctx.typing():
            try:
                async with aiohttp.ClientSession() as session:
                    async with session.post(
                        f"{AI_BASE_URL}/chat/completions",
                        json=payload,
                        headers=headers,
                    ) as response:
                        if response.status != 200:
                            error_text = await response.text()
                            print(f"⚠️ AI Error: {error_text}")
                            return await ctx.send("🔌 **The Plug is sleeping.** (API Error)")
                        data = await response.json()
            except (aiohttp.ClientError, KeyError, TypeError, ValueError) as exc:
                print(f"AI Exception: {exc}")
                return await ctx.send("❌ **Connection Failed.** The Plug is offline.")

        reply = str(data["choices"][0]["message"]["content"])
        if len(reply) > 2000:
            reply = reply[:1990] + "..."
        await ctx.send(reply)

    @commands.hybrid_command(name="imagine", aliases=["draw", "img"])
    @commands.cooldown(1, 30, commands.BucketType.user)
    async def imagine(self, ctx, *, prompt: str):
        """Generate an image using the current server's local balance."""
        if not self.api_key:
            return await ctx.send("❌ API Key missing.")

        try:
            guild_id = require_guild_id(ctx)
        except GuildContextRequired as exc:
            return await ctx.send(f"❌ {exc}.")

        async with self.bot.db.lock:
            profile = await self.bot.db.get_profile(guild_id, ctx.author.id)
            balance = max(0, int(profile.get("grams", 0)))
            if balance < AI_IMAGE_COST:
                return await ctx.send(
                    f"💸 **Art costs money.** You need ${AI_IMAGE_COST}."
                )
            profile["grams"] = balance - AI_IMAGE_COST
            self.bot.db.mark_profile_dirty(guild_id, ctx.author.id)

        message = await ctx.send(
            f"🎨 **Painting:** `{prompt}`... (Cost: ${AI_IMAGE_COST})"
        )
        try:
            image_url = await self._generate_image(prompt)
        except (aiohttp.ClientError, KeyError, TypeError, ValueError) as exc:
            await self._refund_image_cost(guild_id, ctx.author.id)
            return await message.edit(content=f"❌ **Generation Failed. Refunded.** {exc}")

        embed = discord.Embed(
            title="🎨 Generated Art",
            description=prompt,
            color=discord.Color.purple(),
        )
        embed.set_image(url=image_url)
        embed.set_footer(text=f"Generated by {ctx.author.name}")
        await message.edit(content=None, embed=embed)

    async def _generate_image(self, prompt: str) -> str:
        url = "https://api.openai.com/v1/images/generations"
        payload = {
            "model": "dall-e-3",
            "prompt": f"Cool digital art, {prompt}",
            "n": 1,
            "size": "1024x1024",
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        async with aiohttp.ClientSession() as session:
            async with session.post(url, json=payload, headers=headers) as response:
                if response.status != 200:
                    error_text = await response.text()
                    raise ValueError(f"image API returned {response.status}: {error_text[:200]}")
                data = await response.json()
        return str(data["data"][0]["url"])

    async def _refund_image_cost(self, guild_id: int, user_id: int) -> None:
        async with self.bot.db.lock:
            profile = await self.bot.db.get_profile(guild_id, user_id)
            profile["grams"] = max(0, int(profile.get("grams", 0))) + AI_IMAGE_COST
            self.bot.db.mark_profile_dirty(guild_id, user_id)


async def setup(bot):
    await bot.add_cog(AI(bot))
