-- The Plug Minecraft companion bridge
-- Adds read models for the Discloud bot and a narrowly-scoped SECURITY DEFINER
-- ingest RPC for the Paper plugin. The Paper plugin never receives the Supabase
-- service-role key.

begin;

create table if not exists public.minecraft_servers (
    guild_id bigint primary key,
    display_name text not null default 'Minecraft Server',
    host text,
    java_port integer not null default 25565 check (java_port between 1 and 65535),
    bedrock_port integer not null default 19132 check (bedrock_port between 1 and 65535),
    enabled boolean not null default true,
    bridge_instance_id text,
    bridge_version text,
    bridge_last_seen timestamptz,
    minecraft_version text,
    paper_version text,
    tps double precision,
    mspt double precision,
    memory_used_mb bigint,
    memory_max_mb bigint,
    online_players integer,
    max_players integer,
    last_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.minecraft_bridge_auth (
    guild_id bigint primary key references public.minecraft_servers(guild_id) on delete cascade,
    bridge_secret text not null,
    enabled boolean not null default true,
    rotated_at timestamptz not null default now()
);

create table if not exists public.minecraft_players (
    guild_id bigint not null references public.minecraft_servers(guild_id) on delete cascade,
    player_uuid uuid not null,
    username text not null,
    platform text not null default 'java' check (platform in ('java', 'bedrock')),
    discord_user_id bigint,
    first_seen timestamptz,
    last_seen timestamptz not null default now(),
    last_joined_at timestamptz,
    last_left_at timestamptz,
    online boolean not null default false,
    playtime_ticks bigint not null default 0 check (playtime_ticks >= 0),
    world text,
    game_mode text,
    health double precision,
    food integer,
    experience_level integer,
    stats jsonb not null default '{}'::jsonb,
    aura_skills jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now(),
    primary key (guild_id, player_uuid)
);

create index if not exists minecraft_players_guild_online_idx
    on public.minecraft_players (guild_id, online, username);

create index if not exists minecraft_players_guild_discord_idx
    on public.minecraft_players (guild_id, discord_user_id)
    where discord_user_id is not null;

create index if not exists minecraft_players_guild_username_lower_idx
    on public.minecraft_players (guild_id, lower(username));

create table if not exists public.minecraft_activity (
    id bigint generated by default as identity primary key,
    guild_id bigint not null references public.minecraft_servers(guild_id) on delete cascade,
    player_uuid uuid,
    username text,
    event_type text not null check (event_type in ('join', 'quit', 'death', 'advancement')),
    detail text,
    occurred_at timestamptz not null default now()
);

create index if not exists minecraft_activity_guild_time_idx
    on public.minecraft_activity (guild_id, occurred_at desc);

-- Nobody using anon/authenticated REST credentials can read the bridge secret or
-- write these tables directly. The trusted Discloud process uses the service role,
-- while the Paper plugin can only execute the ingest function below.
alter table public.minecraft_servers enable row level security;
alter table public.minecraft_bridge_auth enable row level security;
alter table public.minecraft_players enable row level security;
alter table public.minecraft_activity enable row level security;

revoke all on table public.minecraft_servers from anon, authenticated;
revoke all on table public.minecraft_bridge_auth from anon, authenticated;
revoke all on table public.minecraft_players from anon, authenticated;
revoke all on table public.minecraft_activity from anon, authenticated;

create or replace function public.the_plug_bridge_ingest(
    p_guild_id bigint,
    p_secret text,
    p_server jsonb,
    p_players jsonb default '[]'::jsonb,
    p_events jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    expected_secret text;
    player_count integer := 0;
    event_count integer := 0;
begin
    if p_guild_id is null or p_guild_id <= 0 then
        raise exception 'invalid guild id' using errcode = '22023';
    end if;

    select bridge_secret
      into expected_secret
      from public.minecraft_bridge_auth
     where guild_id = p_guild_id
       and enabled = true;

    if expected_secret is null
       or p_secret is null
       or length(p_secret) < 24
       or expected_secret <> p_secret then
        raise exception 'invalid bridge credentials' using errcode = '28000';
    end if;

    -- The configuration/address fields are controlled by the trusted Discord bot.
    -- The bridge only updates runtime telemetry.
    update public.minecraft_servers
       set bridge_instance_id = nullif(p_server->>'bridge_instance_id', ''),
           bridge_version = nullif(p_server->>'bridge_version', ''),
           bridge_last_seen = now(),
           minecraft_version = nullif(p_server->>'minecraft_version', ''),
           paper_version = nullif(p_server->>'paper_version', ''),
           tps = case
               when p_server ? 'tps' then (p_server->>'tps')::double precision
               else tps
           end,
           mspt = case
               when p_server ? 'mspt' then (p_server->>'mspt')::double precision
               else mspt
           end,
           memory_used_mb = case
               when p_server ? 'memory_used_mb' then (p_server->>'memory_used_mb')::bigint
               else memory_used_mb
           end,
           memory_max_mb = case
               when p_server ? 'memory_max_mb' then (p_server->>'memory_max_mb')::bigint
               else memory_max_mb
           end,
           online_players = case
               when p_server ? 'online_players' then (p_server->>'online_players')::integer
               else online_players
           end,
           max_players = case
               when p_server ? 'max_players' then (p_server->>'max_players')::integer
               else max_players
           end,
           last_snapshot = coalesce(p_server, '{}'::jsonb),
           updated_at = now()
     where guild_id = p_guild_id
       and enabled = true;

    if not found then
        raise exception 'minecraft server is not configured or is disabled'
            using errcode = 'P0002';
    end if;

    -- A heartbeat is authoritative for who is online. Flip the previous online
    -- set to offline, then the current payload below turns active players back on.
    update public.minecraft_players
       set online = false,
           last_left_at = now(),
           updated_at = now()
     where guild_id = p_guild_id
       and online = true;

    if jsonb_typeof(coalesce(p_players, '[]'::jsonb)) <> 'array' then
        raise exception 'p_players must be a JSON array' using errcode = '22023';
    end if;

    insert into public.minecraft_players (
        guild_id,
        player_uuid,
        username,
        platform,
        discord_user_id,
        first_seen,
        last_seen,
        last_joined_at,
        online,
        playtime_ticks,
        world,
        game_mode,
        health,
        food,
        experience_level,
        stats,
        aura_skills,
        updated_at
    )
    select
        p_guild_id,
        x.player_uuid,
        left(coalesce(nullif(x.username, ''), 'Unknown'), 100),
        case when lower(x.platform) = 'bedrock' then 'bedrock' else 'java' end,
        x.discord_user_id,
        x.first_seen,
        now(),
        x.joined_at,
        true,
        greatest(coalesce(x.playtime_ticks, 0), 0),
        left(x.world, 150),
        left(x.game_mode, 40),
        x.health,
        x.food,
        x.experience_level,
        coalesce(x.stats, '{}'::jsonb),
        coalesce(x.aura_skills, '{}'::jsonb),
        now()
    from jsonb_to_recordset(coalesce(p_players, '[]'::jsonb)) as x(
        player_uuid uuid,
        username text,
        platform text,
        discord_user_id bigint,
        first_seen timestamptz,
        joined_at timestamptz,
        playtime_ticks bigint,
        world text,
        game_mode text,
        health double precision,
        food integer,
        experience_level integer,
        stats jsonb,
        aura_skills jsonb
    )
    on conflict (guild_id, player_uuid) do update
       set username = excluded.username,
           platform = excluded.platform,
           discord_user_id = excluded.discord_user_id,
           first_seen = coalesce(public.minecraft_players.first_seen, excluded.first_seen),
           last_seen = now(),
           last_joined_at = coalesce(excluded.last_joined_at, public.minecraft_players.last_joined_at),
           online = true,
           playtime_ticks = excluded.playtime_ticks,
           world = excluded.world,
           game_mode = excluded.game_mode,
           health = excluded.health,
           food = excluded.food,
           experience_level = excluded.experience_level,
           stats = excluded.stats,
           aura_skills = excluded.aura_skills,
           updated_at = now();

    get diagnostics player_count = row_count;

    if jsonb_typeof(coalesce(p_events, '[]'::jsonb)) <> 'array' then
        raise exception 'p_events must be a JSON array' using errcode = '22023';
    end if;

    insert into public.minecraft_activity (
        guild_id,
        player_uuid,
        username,
        event_type,
        detail,
        occurred_at
    )
    select
        p_guild_id,
        x.player_uuid,
        left(x.username, 100),
        lower(x.event_type),
        left(x.detail, 500),
        coalesce(x.occurred_at, now())
    from jsonb_to_recordset(coalesce(p_events, '[]'::jsonb)) as x(
        player_uuid uuid,
        username text,
        event_type text,
        detail text,
        occurred_at timestamptz
    )
    where lower(x.event_type) in ('join', 'quit', 'death', 'advancement');

    get diagnostics event_count = row_count;

    -- This is a live activity feed, not permanent surveillance/history.
    delete from public.minecraft_activity
     where guild_id = p_guild_id
       and occurred_at < now() - interval '30 days';

    return jsonb_build_object(
        'ok', true,
        'players', player_count,
        'events', event_count,
        'received_at', now()
    );
end;
$$;

revoke all on function public.the_plug_bridge_ingest(bigint, text, jsonb, jsonb, jsonb)
    from public;
grant execute on function public.the_plug_bridge_ingest(bigint, text, jsonb, jsonb, jsonb)
    to anon, authenticated, service_role;

insert into public.app_schema_migrations (version)
values ('003_minecraft_companion')
on conflict (version) do nothing;

commit;
